[package]
name = "manifold-view"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.17.3", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_log",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_winit",
    "bevy_window",
    "zstd_rust",
    "tonemapping_luts",
    "multi_threaded",
] }
anyhow = "1"
stl_io = "0.10.0"
